name: sms_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  permission_handler: ^11.4.0
  telephony_plugin:
    path: ./telephony_plugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.5
  flutter_launcher_icons: ^0.13.1 

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/icon/icon.png"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
  macos:
    generate: true
    image_path: "assets/icon/icon.png"  

flutter_native_splash:
  color: "#ffffff"  # Background color
  image: assets/splash/splash.png  # Your splash image
  color_dark: "#121212"  # Background color for dark mode (optional)
  image_dark: assets/splash/splash.png  # Splash image for dark mode (optional)
  
  android_12:
    image: assets/splash/splash.png
    icon_background_color: "#ffffff"
    
  web: false  # You can set to true if you want web splash
  fullscreen: true  # Optional, hides status bar    

flutter:
  uses-material-design: true

assets:
    - assets/icon/
    - assets/splash/